name: Run DTDC to BIK Tracking

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour at 00 minutes
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  run-tracking:
    runs-on: windows-latest
    env:
      SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
      SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
      DTDC_TOKEN: ${{ secrets.DTDC_TOKEN }}
      DTDC_URL: ${{ secrets.DTDC_URL }}
      BIK_WEBHOOK_URL: ${{ secrets.BIK_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./tracking.ps1
