name: Run DTDC to BIK Tracking

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 * * * *'    # every hour, 24/7

jobs:
  run-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     - name: Run PowerShell script
       shell: pwsh
       run: ./my-tracker.ps1


