name: Run DTDC to BIK Tracking

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes

jobs:
  run-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        shell: pwsh
        run: ./my-tracker.ps1
        env:
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          DTDC_TOKEN: ${{ secrets.DTDC_TOKEN }}
          DTDC_URL: ${{ secrets.DTDC_URL }}
          BIK_WEBHOOK_URL: ${{ secrets.BIK_WEBHOOK_URL }}

      - name: Upload log file
        uses: actions/upload-artifact@v3
        with:
          name: tracking-log
          path: ./dtdc_to_bik_log.txt
